force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Policy_Type__c.field-meta.xml
<CustomField>
    <fullName>Policy_Type__c</fullName>
    <label>Policy Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Vehicle</fullName>
            </value>
            <value>
                <fullName>Property</fullName>
            </value>
            <value>
                <fullName>Life</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Line_Item__c/Policy_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Policy Line Item</label>
    <nameField>
        <label>Polic Line Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Police Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Line_Item__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Police Line Items</relationshipLabel>
    <relationshipName>Police_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Policy_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Inprogress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Policy.cls
public with sharing class Policy {
    public static void policyRecord() {
        Account acc=new Account();
        acc.name = 'deepa';
       acc.Amount__c=10001;
        insert acc;
        Policy__c Pl = new Policy__c();
		Pl.name = 'Pl1';
        pl.Account__c = acc.Id;
        Pl.Policy_Type__c = 'Health';
        insert Pl;
        Policy_Line_Item__c PLI = new Policy_Line_Item__c();
        PLI.name = 'PLI1';
        PLI.Policy__c = Pl.Id;
        PLI.Status__c = 'open';
        insert PLI;




    }
}