force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Policy_Number__c.field-meta.xml
<CustomField>
    <fullName>Policy_Number__c</fullName>
    <displayFormat>PL-{0000}</displayFormat>
    <label>Policy Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Policy_Line_Item__c/Policy_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Policy Line Item</label>
    <nameField>
        <label>Polic Line Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Police Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Line_Item__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Police Line Items</relationshipLabel>
    <relationshipName>Police_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PolicyNumberRestAPI.cls
@RestResource(urlMapping='/test/*')
    global class PolicyNumberRestAPI{
        @HttpGet
        global static Policy__c doGet(){
            RestRequest req=RestContext.request;
            RestResponse res=RestContext.response;
            String plId= req.requestURI.SubString(req.RequestURI.lastIndexOf('/')+1);
             Policy__c Result=[Select id , (Select id,Name From Police_Line_Items__r)From Policy__c Where Policy_Number__c =:plId]; 
               return Result;                                   
        }
        @HttpPost
        global static Policy__c doPost(String Name, String Name2){
            Policy__c pl=new Policy__c();
            pl.Name=Name;
            insert pl;
            Policy_Line_Item__c plm=new Policy_Line_Item__c();
            plm.Name=Name2;
            plm.Policy__c=pl.Id;
            insert plm;
            Policy__c Result=[Select id,Name,(Select id,Name From Police_Line_Items__r) From Policy__c Where Id =: pl.Id];
            return Result;
            
        }
        
        
    
    }