force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Line_Item__c/Policy_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Policy Line Item</label>
    <nameField>
        <label>Polic Line Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Police Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Line_Item__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Police Line Items</relationshipLabel>
    <relationshipName>Police_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PolicyLineItems.cls
public with sharing class PolicyLineItems {
        public static void lineItemsInPolicy(){
            List<Policy__c> PList = new List<Policy__c>();
            for(Integer i=0; i<9; i++)
            {
               Policy__c P = new Policy__c();
               P.Name= 'Mahesh'+ i;
               PList.add(P);
            }
           insert PList;
          List<Policy_Line_Item__c> PlList = new List<Policy_Line_Item__c>();
                for (Policy__c P : PList)
                {
               Policy_Line_Item__c Pl = new Policy_Line_Item__c();
               Pl.Name= 'Deepa';
               Pl.Policy__c= P.Id;
                PlList.add(Pl);
            }   
            insert PlList;
        }
    
    }