force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Line_Item__c/Policy_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Policy Line Item</label>
    <nameField>
        <label>Polic Line Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Police Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Line_Item__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Police Line Items</relationshipLabel>
    <relationshipName>Police_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Insertplitem.cls
public class Insertplitem {
        public static void insertPlitem12(){
            List<Policy__c> pslist =[SELECT Id, Name, (SELECT Id , Policy__c , name FROM Police_Line_Items__r) FROM Policy__c];
            List< Policy_Line_Item__c> pn = new  List<Policy_Line_Item__c>();
            for(Policy__c a : pslist){
              if(  a.Police_Line_Items__r.size()==0){
                  Policy_Line_Item__c pl=new Policy_Line_Item__c();
                  pl.Name='deepa';
                  pl.Policy__c=a.id;
                  pn.add(pl);
              }
              
          }
            insert pn;
        }
      }