force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Errorlog</label>
    <nameField>
        <label>Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Errorlogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <label>Error</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Errormessages.cls
public with sharing class Errormessages {
        public static void errorLog() {
        try{
        Account acclist=[SELECT Id, name,Phone FROM Account];
        List<Contact> Con = [SELECT Id, Account.Phone FROM Contact];
        list<Contact> Conlist =new list<Contact>();
            for(Contact c : Con){
                c.Phone = c.Account.Phone ;
                Conlist.add(c);
            }

        if( Conlist != Null && !Conlist.isEmpty())
        {
            update +Conlist;
        }
        }
        catch(Exception e){
            Error_Log__c elog = new Error_Log__c();
            if(e != Null){
              elog.Name='nani';
            elog.Error__c= e.getMessage();                                                                                
                                       }
            insert elog;
                Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
          message.toAddresses = new String[] { 'deeparaniamudalapalli12@gmail.com' };
                                      }
                                    }
                                  }